import { Product, Course, RangeBuild, Instructor } from '@/types';

export const products: Product[] = [
  {
    id: '1',
    slug: 'bts-nv14-gen3-monocular',
    model: 'BTS-NV14',
    name: 'Gen 3+ Monocular',
    category: 'night-vision',
    subcategory: 'monocular',
    description: 'High-performance Gen 3+ autogated night vision monocular with manual gain control. Designed for military and law enforcement operations requiring compact, lightweight observation capability.',
    specs: [
      { label: 'Resolution', value: '64-72 lp/mm' },
      { label: 'FOV', value: '40°' },
      { label: 'Detection Range', value: '550m' },
      { label: 'Weight', value: '320g' },
      { label: 'Battery Life', value: '50 hrs' },
      { label: 'Magnification', value: '1x (3x optional)' },
      { label: 'Tube Type', value: 'Gen 3+ Autogated' },
      { label: 'IP Rating', value: 'IP67' },
    ],
    markets: ['MIL', 'LE', 'CIV'],
    price: null,
    images: [],
  },
  {
    id: '2',
    slug: 'bts-nv31-binocular',
    model: 'BTS-NV31',
    name: 'Gen 3 Binocular Goggle',
    category: 'night-vision',
    subcategory: 'binocular',
    description: 'Dual-tube binocular night vision goggle with depth perception capability. Purpose-built for dismounted operations, CQB, and driving applications.',
    specs: [
      { label: 'Resolution', value: '64-72 lp/mm' },
      { label: 'FOV', value: '40° per eye' },
      { label: 'Detection Range', value: '600m' },
      { label: 'Weight', value: '560g' },
      { label: 'Battery Life', value: '40 hrs' },
      { label: 'Magnification', value: '1x' },
      { label: 'Tube Type', value: 'Gen 3 White Phosphor' },
      { label: 'IP Rating', value: 'IP67' },
    ],
    markets: ['MIL', 'LE'],
    price: null,
    images: [],
  },
  {
    id: '3',
    slug: 'bts-th640-thermal-weapon-sight',
    model: 'BTS-TH640',
    name: 'Thermal Weapon Sight',
    category: 'thermal',
    subcategory: 'weapon-mounted',
    description: 'High-resolution 640x480 thermal weapon sight with multiple reticle options and ballistic calculator. Optimized for precision engagement from 50 to 1500 meters.',
    specs: [
      { label: 'Resolution', value: '640×480' },
      { label: 'FOV', value: '12.5° × 9.4°' },
      { label: 'Detection Range', value: '2,200m' },
      { label: 'Weight', value: '890g' },
      { label: 'Battery Life', value: '8 hrs' },
      { label: 'Magnification', value: '2-8x digital' },
      { label: 'Sensor', value: '12μm VOx' },
      { label: 'Refresh Rate', value: '60Hz' },
    ],
    markets: ['MIL', 'LE'],
    price: null,
    images: [],
  },
  {
    id: '4',
    slug: 'bts-th384-handheld',
    model: 'BTS-TH384',
    name: 'Thermal Handheld Imager',
    category: 'thermal',
    subcategory: 'handheld',
    description: 'Compact thermal handheld imager with built-in display and video recording. Ideal for surveillance, search and rescue, and perimeter security operations.',
    specs: [
      { label: 'Resolution', value: '384×288' },
      { label: 'FOV', value: '17.5° × 13.1°' },
      { label: 'Detection Range', value: '1,500m' },
      { label: 'Weight', value: '410g' },
      { label: 'Battery Life', value: '6 hrs' },
      { label: 'Magnification', value: '1-4x digital' },
      { label: 'Sensor', value: '17μm VOx' },
      { label: 'Refresh Rate', value: '50Hz' },
    ],
    markets: ['MIL', 'LE', 'CIV'],
    price: 4200,
    images: [],
  },
  {
    id: '5',
    slug: 'bts-nv-clip-on',
    model: 'BTS-NVCO',
    name: 'Night Vision Clip-On',
    category: 'night-vision',
    subcategory: 'clip-on',
    description: 'Universal clip-on night vision device that mounts forward of existing day optics. Convert any standard riflescope into a night-capable system without re-zeroing.',
    specs: [
      { label: 'Resolution', value: '57-64 lp/mm' },
      { label: 'FOV', value: '22°' },
      { label: 'Detection Range', value: '800m' },
      { label: 'Weight', value: '680g' },
      { label: 'Battery Life', value: '60 hrs' },
      { label: 'Magnification', value: '1x' },
      { label: 'Tube Type', value: 'Gen 3 Filmless' },
      { label: 'IP Rating', value: 'IP68' },
    ],
    markets: ['MIL', 'LE', 'CIV'],
    price: null,
    images: [],
  },
  {
    id: '6',
    slug: 'bts-th320-clip-on',
    model: 'BTS-THCO',
    name: 'Thermal Clip-On System',
    category: 'thermal',
    subcategory: 'clip-on',
    description: 'Compact thermal clip-on system for forward mounting on existing day scopes. Features edge detection mode for enhanced target identification.',
    specs: [
      { label: 'Resolution', value: '320×256' },
      { label: 'FOV', value: '7.5° × 5.6°' },
      { label: 'Detection Range', value: '1,800m' },
      { label: 'Weight', value: '520g' },
      { label: 'Battery Life', value: '7 hrs' },
      { label: 'Magnification', value: '1x' },
      { label: 'Sensor', value: '12μm VOx' },
      { label: 'Refresh Rate', value: '60Hz' },
    ],
    markets: ['MIL', 'LE', 'CIV'],
    price: 5800,
    images: [],
  },
];

export const courses: Course[] = [
  {
    id: '1',
    slug: 'precision-rifle-fundamentals',
    name: 'Precision Rifle I: Fundamentals',
    category: 'long-range',
    skillLevel: 'beginner',
    description: 'Foundation course covering rifle marksmanship principles, ballistic fundamentals, scope operation, and positional shooting out to 600 yards.',
    duration: '3 Days',
    format: 'In-Person, Instructor-Led',
    date: '2025-04-15',
    location: 'Colorado Springs, CO',
    spotsRemaining: 8,
    price: 1200,
    includes: ['Classroom instruction', 'Live-fire range time', '200 rounds provided', 'Ballistic calculator setup', 'Course completion certificate'],
  },
  {
    id: '2',
    slug: 'precision-rifle-advanced',
    name: 'Precision Rifle II: Advanced Long Range',
    category: 'long-range',
    skillLevel: 'advanced',
    description: 'Advanced course covering engagements from 600 to 1,500 yards. Wind reading, moving targets, elevated/depressed angle shooting, and field craft.',
    duration: '4 Days',
    format: 'In-Person, Instructor-Led',
    date: '2025-05-10',
    location: 'Colorado Springs, CO',
    spotsRemaining: 4,
    price: 1800,
    includes: ['Advanced ballistic theory', 'Live-fire to 1 mile', '300 rounds provided', 'Wind reading clinic', 'Positional shooting drills'],
  },
  {
    id: '3',
    slug: 'defensive-pistol-fundamentals',
    name: 'Defensive Pistol: Fundamentals',
    category: 'pistol',
    skillLevel: 'beginner',
    description: 'Core pistol marksmanship course covering grip, stance, sight alignment, trigger control, draw from holster, and basic defensive scenarios.',
    duration: '2 Days',
    format: 'In-Person, Instructor-Led',
    date: '2025-04-20',
    location: 'Colorado Springs, CO',
    spotsRemaining: 12,
    price: 650,
    includes: ['Classroom fundamentals', 'Live-fire drills', '400 rounds provided', 'Holster work', 'Safety certification'],
  },
  {
    id: '4',
    slug: 'low-light-pistol',
    name: 'Defensive Pistol: Low-Light Operations',
    category: 'pistol',
    skillLevel: 'advanced',
    description: 'Specialized low-light and no-light pistol operations. Weapon-mounted light techniques, handheld light methods, target identification, and shoot/no-shoot scenarios.',
    duration: '2 Days',
    format: 'In-Person, Instructor-Led',
    date: '2025-06-05',
    location: 'Colorado Springs, CO',
    spotsRemaining: 6,
    price: 850,
    includes: ['Low-light theory', 'Night-fire exercises', '500 rounds provided', 'Light/laser equipment use', 'Force-on-force scenarios'],
  },
  {
    id: '5',
    slug: 'concealed-carry-proficiency',
    name: 'Concealed Carry Proficiency',
    category: 'pistol',
    skillLevel: 'intermediate',
    description: 'Focused on the skills needed for effective concealed carry. Drawing from concealment, threat assessment, legal considerations, and scenario-based training.',
    duration: '1 Day',
    format: 'In-Person, Instructor-Led',
    date: '2025-04-28',
    location: 'Colorado Springs, CO',
    spotsRemaining: 15,
    price: 400,
    includes: ['Legal overview', 'Draw from concealment drills', '200 rounds provided', 'Scenario training', 'Certificate of completion'],
  },
  {
    id: '6',
    slug: 'custom-range-program',
    name: 'Custom Range Operations Program',
    category: 'custom',
    skillLevel: 'professional',
    description: 'Fully customized training program designed for your facility and team. Includes curriculum development, instructor placement, and ongoing program management.',
    duration: 'Custom',
    format: 'In-Person, Instructor-Led',
    date: 'By Arrangement',
    location: 'Your Facility',
    spotsRemaining: 0,
    price: 0,
    includes: ['Needs assessment', 'Custom curriculum design', 'Instructor placement', 'Program management', 'Performance tracking'],
  },
];

export const rangeBuilds: RangeBuild[] = [
  {
    id: '1',
    name: 'Fort Collins Indoor Range',
    location: 'Fort Collins, CO',
    type: 'Indoor',
    lanes: 20,
    maxDistance: '50 yards',
    image: '',
  },
  {
    id: '2',
    name: 'Mesa Tactical Center',
    location: 'Mesa, AZ',
    type: 'Indoor/Outdoor',
    lanes: 30,
    maxDistance: '200 yards',
    image: '',
  },
  {
    id: '3',
    name: 'Camp Bravo Long Range Complex',
    location: 'West Texas',
    type: 'Outdoor',
    lanes: 12,
    maxDistance: '2,000 yards',
    image: '',
  },
  {
    id: '4',
    name: 'Summit County Public Safety Range',
    location: 'Frisco, CO',
    type: 'Indoor',
    lanes: 15,
    maxDistance: '25 yards',
    image: '',
  },
];

export const instructors: Instructor[] = [
  {
    id: '1',
    name: 'Jake Morrison',
    credentials: 'US Army Special Forces (Ret.), 22 years service',
    specialty: 'Long Range Precision, Field Craft',
    bio: 'Former 18B weapons sergeant with multiple combat deployments. Sniper school graduate and long-range marksmanship instructor.',
    image: '',
  },
  {
    id: '2',
    name: 'Maria Santos',
    credentials: 'FBI HRT (Ret.), NRA Master Instructor',
    specialty: 'Pistol, Defensive Tactics',
    bio: 'Former FBI Hostage Rescue Team operator and firearms instructor. Specializes in defensive pistol and force-on-force training.',
    image: '',
  },
  {
    id: '3',
    name: 'David Chen',
    credentials: 'USMC Scout Sniper (Ret.), Ballistic Engineer',
    specialty: 'Ballistics, Optics, Night Vision',
    bio: 'Marine Scout Sniper turned optical engineer. Leads Breaker optics R&D and instructs advanced ballistics courses.',
    image: '',
  },
];
